routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::post('/reportar', 'HomeController@postReport')->name('createReport');
Route::get('/reportar', 'HomeController@getReport');

Route::group(['middleware' => 'admin', 'namespace' => 'Admin'], function() {
    // Usuarios
    Route::resource('/usuarios', 'UserController');
    Route::get('/usuarios/{usuarios}/restaurar', 'UserController@restore')->name('usuarios.restore');
    //Proyectos
    Route::resource('/proyectos', 'ProyectoController');
    Route::get('/proyectos/{proyecto}/restaurar', 'ProyectoController@restore')->name('proyectos.restore');
    //Categoria
    Route::resource('/categorias', 'CategoryController');
    Route::get('/categorias/{categoria}/restaurar', 'CategoryController@restore')->name('categorias.restore');
    //Level
    Route::resource('/levels', 'LevelController');
    Route::get('/levels/{level}/restaurar', 'LevelController@restore')->name('levels.restore');

    //Project UserController
    Route::post('/proyecto-usuario', 'ProjectUserController@store')->name('proyecto.usuario');
    Route::delete('/proyecto-usuario/{id}/eliminar', 'ProjectUserController@delete')->name('proyecto.usuario.delete');

    Route::get('/config', 'ConfigController@index');
});

app/User.php
<?php

namespace App;

use App\project;

use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use SoftDeletes;
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','role',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function getIsAdminAttribute(){
        return $this->role == 0;
    }

    public function getIsClientAttribute(){
        return $this->role == 2;
    }

    public function projects()
    {
      return $this->belongsToMany('App\project');
    }

    public function getListOfProjectsAttribute()
    {
      if($this->role == 1){
        return $this->projects;
      }else {
        return project::all();
      }
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\User;
use App\project;
use App\level;
use App\ProjectUser;
use App\Http\Controllers\Controller;

class UserController extends Controller
{
    public function index()
    {
        $users = User::withTrashed()->where('role', 1)->get();
        return view('admin.users.index', compact('users'));
    }

    public function create()
    {

    }

    public function store(Request $request)
    {
        $rules = [
            'name' => 'required|string|max:255',
            'email' => 'required|string|email|max:255|unique:users',
            'password' => 'required|string|min:6',
        ];

        $message = [
            'name.required' => 'Es necesario ingresar el nombre',
            'name.max' => 'No se puede pasar de 255 caracteres',
            'email.required' => 'Email es requerido',
            'email.email' => 'El dato no es un email',
            'email.max' => 'El campo no puede tener mas de 255 caracteres',
            'email.unique' => 'El email ya existe',
            'password.required' => 'Es necesario ingresar contraseña',
            'password.min' => 'La contraseña debe tener como minimo 6 caracteres'
        ];

        $this->validate($request, $rules, $message);

        $user = new User();
        $user->name = $request->name;
        $user->email = $request->email;
        $user->password = bcrypt($request->password);
        $user->role = 1;
        $user->save();

        return back()->with('notification', 'Registro Exitoso');
    }

    public function show($id)
    {

    }

    public function edit($id)
    {
        $user = User::find($id);
        $projects = project::all();
        $projects_user = ProjectUser::where('user_id', $user->id)->get();

        return view('admin.users.edit', compact('user', 'projects', 'projects_user'));
    }

    public function update(Request $request, $id)
    {

        if($request->password){
            $rules = [
                'name' => 'required|max:255',
                'password' => 'min:6'
            ];
        }else{
            $rules = [
                'name' => 'required|max:255',
            ];
        }

        $message = [
            'name.required' => 'Es necesario ingresar el nombre de usuario',
            'name.max' => 'El nombre es demasiado largo',
            'password.min' => 'La contraseña debe tener minimo 6 caracteres'
        ];

        $this->validate($request, $rules, $message);

        $user = User::find($id);

        $user->name = $request->name;
        $password = $request->password;

        if($password){
            $user->password = bcrypt($password);
        }

        $user->save();

        return back();
    }

    public function destroy($id)
    {
        $user = User::find($id);
        //User::destroy($id);
        $user->delete();

        return back();
    }

    public function restore($id)
    {
        User::withTrashed()->find($id)->restore();

        return back()->with('notification', 'EL usuario se ha habilitado correctamente');
    }
}

resources/views/admin/users/edit.blade.php
@extends('layouts.app')

@section('content')

<div class="card">
    <div class="card-header">Registrar Usuario</div>
    <div class="card-body">
        @include('messageSuccess')
        @include('messageError')
        <form action="{{route('usuarios.update', $user->id)}}" method="POST">
            {{ csrf_field() }}
            {{ method_field('PATCH')}}


            <!-- Name -->
            <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                <label for="name">Name</label>
                <input id="name" type="text" class="form-control" name="name" value="{{ old('name', $user->name )}}" required autofocus>
                    @if ($errors->has('name'))
                        <span class="help-block">
                            <strong>{{ $errors->first('name') }}</strong>
                        </span>
                    @endif
            </div>

            <!-- Email -->
            <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                <label for="email">E-Mail Address</label>
                <input id="email" type="email" class="form-control" name="email" value="{{ old('email',  $user->email) }}" readonly required>
                    @if ($errors->has('email'))
                        <span class="help-block">
                            <strong>{{ $errors->first('email') }}</strong>
                        </span>
                    @endif
            </div>

            <!-- Password -->
            <div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
                <label for="password">Password <em>Si deseas cambiar la clave</em></label>
                <input id="password" type="text" class="form-control" name="password" value="{{ old('password')}}">
                    @if ($errors->has('password'))
                        <span class="help-block">
                            <strong>{{ $errors->first('password') }}</strong>
                        </span>
                    @endif
            </div>

            <div class="form-group">
                <button type="submit" class="btn btn-primary">Guardar</button>
            </div>

        </form>

        <!-- sleect proyecto y nivel mas boton asignar proyecto -->
        <form action="{{route('proyecto.usuario')}}" method="post">
          {{ csrf_field() }}
        <div class="row">
            <input type="hidden" name="user_id" value="{{$user->id}}">
          <div class="col-md-4">
            <div class="form-group">
                <select name="project_id" class="form-control" id="select-project">
                    <option selected="">Seleccione proyecto</option>
                    @foreach ($projects as $key => $project)
                      <option value="{{$project->id}}">{{$project->name}}</option>
                    @endforeach
                </select>
            </div>
          </div>
          <div class="col-md-4">
            <div class="form-group">
                <select name="level_id" class="form-control" id="select-level">
                    <option selected="">Seleccione nivel</option>
                </select>
            </div>
          </div>
          <div class="col-md-4">
            <div class="form-group">
                <button type="submit" class="btn btn-primary">Asignar proyecto</button>
            </div>
          </div>
        </div>
        </form>

        <div class="card">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th scope="col"> # </th>
                        <th scope="col">Proyecto</th>
                        <th scope="col">Nivel</th>
                        <th scope="col">Opciones</th>
                    </tr>
                </thead>
                <tbody>
                  @foreach ($projects_user as $key => $project_user)
                    <tr class="table-active">
                        <th scope="row">{{$key+1}}</th>
                        <td>{{$project_user->project->name}}</td>
                        <td>{{$project_user->level->name}}</td>
                        <td>
                            <form action="{{route('proyecto.usuario.delete', $project_user->id)}}" method="post">
                              {{ csrf_field() }}
                              {{ method_field('DELETE')}}
                              <button  class="btn btn-sm btn-danger" title="Eliminar" type="submit" name="button"><i class="fas fa-trash-alt"></i></button>
                            </form>
                        </td>
                    </tr>
                  @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>

@endsection

resources/views/admin/users/index.blade.php
@extends('layouts.app')

@section('content')

<div class="card">
    <div class="card-header">Registrar Usuario</div>
    <div class="card-body">
        @include('messageError')
        @include('messageSuccess')

        <form action="{{route('usuarios.store')}}" method="POST">
            {{ csrf_field() }}

            <!-- Name -->
            <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                <label for="name">Name</label>
                <input id="name" type="text" class="form-control" name="name" value="{{ old('name') }}" required autofocus>
                    @if ($errors->has('name'))
                        <span class="help-block">
                            <strong>{{ $errors->first('name') }}</strong>
                        </span>
                    @endif
            </div>

            <!-- Email -->
            <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                <label for="email">E-Mail Address</label>
                <input id="email" type="email" class="form-control" name="email" value="{{ old('email') }}" required>
                    @if ($errors->has('email'))
                        <span class="help-block">
                            <strong>{{ $errors->first('email') }}</strong>
                        </span>
                    @endif
            </div>

            <!-- Password -->
            <div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
                <label for="password">Password</label>
                <input id="password" type="text" class="form-control" name="password" value="{{ old('password', str_random(8)) }}" required>
                    @if ($errors->has('password'))
                        <span class="help-block">
                            <strong>{{ $errors->first('password') }}</strong>
                        </span>
                    @endif
            </div>

            <!-- Boton Agregar -->
            <div class="form-group">
                <button class="btn btn-primary">Registrar</button>
            </div>
        </form>

        <div class="card">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th scope="col"> Id </th>
                        <th scope="col">E-mail</th>
                        <th scope="col">Nombre</th>
                        <th scope="col">Opciones</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($users as $user)
                    <tr class="table-active">
                        <th scope="row">{{$user->id}}</th>
                        <td>{{$user->email}}</td>
                        <td>{{$user->name}}</td>
                        <td>

                            <form action="{{route('usuarios.destroy', $user->id)}}" method="POST">
                                {{ csrf_field() }}
                                {{ method_field('DELETE')}}

                                @if($user->trashed())
                                    <a class="btn btn-sm btn-info" title="Restaurar" href="{{route('usuarios.restore', $user->id)}}"><i class="fas fa-undo"></i></a>
                                @else
                                    <a class="btn btn-sm btn-primary" title="Editar" href="{{route('usuarios.edit', $user->id)}}"><i class="fas fa-edit"></i></a>
                                    <button class="btn btn-sm btn-danger" title="Eliminar" ><i class="fas fa-trash-alt"></i></button>
                                @endif
                            </form>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>

@endsection