routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::post('/reportar', 'HomeController@postReport')->name('createReport');
Route::get('/reportar', 'HomeController@getReport');

Route::group(['middleware' => 'admin', 'namespace' => 'Admin'], function() {
    // Usuarios
    Route::resource('/usuarios', 'UserController');
    Route::get('/usuarios/{usuarios}/restaurar', 'UserController@restore')->name('usuarios.restore');
    //Proyectos
    Route::resource('/proyectos', 'ProyectoController');
    Route::get('/proyectos/{proyecto}/restaurar', 'ProyectoController@restore')->name('proyectos.restore');
    //Categoria
    Route::resource('/categorias', 'CategoryController');
    Route::get('/categorias/{categoria}/restaurar', 'CategoryController@restore')->name('categorias.restore');
    //Level
    Route::resource('/levels', 'LevelController');
    Route::get('/levels/{level}/restaurar', 'LevelController@restore')->name('levels.restore');

    //Project UserController
    Route::post('/proyecto-usuario', 'ProjectUserController@store')->name('proyecto.usuario');
    Route::delete('/proyecto-usuario/{id}/eliminar', 'ProjectUserController@delete')->name('proyecto.usuario.delete');

    Route::get('/config', 'ConfigController@index');
});

app/User.php
<?php

namespace App;

use App\project;

use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use SoftDeletes;
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','role',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function getIsAdminAttribute(){
        return $this->role == 0;
    }

    public function getIsClientAttribute(){
        return $this->role == 2;
    }

    public function projects()
    {
      return $this->belongsToMany('App\project');
    }

    public function getListOfProjectsAttribute()
    {
      if($this->role == 1){
        return $this->projects;
      }else {
        return project::all();
      }
    }
}

resources/views/includes/menu.blade.php
<div class="card">

        <div class="card-header">Menu</div>
        <div class="card-body">

            <div class="list-group">
                @if(auth()->check())

                    <a href="/home" class="list-group-item list-group-item-action">
                        Dashboard
                    </a>

                    @if(! auth()->user()->is_client)
                        <a href="#" class="list-group-item list-group-item-action">
                            Ver incidencias
                        </a>
                    @endif
                    <a href="/reportar" class="list-group-item list-group-item-action">
                        Reportar incidencias
                    </a>

                    <!-- DropDow de menu -->

                    @if(auth()->user()->is_admin)
                        <a class="list-group-item list-group-item-action dropdown dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Administracion</a>
                        <div class="dropdown-menu" x-placement="bottom-start" style="position: absolute; transform: translate3d(0px, 40px, 0px); top: 0px; left: 0px; will-change: transform;">
                        <a class="dropdown-item" href="{{route('usuarios.index')}}">Usuarios</a>
                        <a class="dropdown-item" href="{{route('proyectos.index')}}">Proyectos</a>
                        <a class="dropdown-item" href="/config">Configuracion</a>
                        </div>
                    @endif
                      


                @else

                    <a href="/" class="list-group-item list-group-item-action">
                        Bienvenido
                    </a>
                    <a href="#" class="list-group-item list-group-item-action">
                        Instrucciones
                    </a>
                    <a href="#" class="list-group-item list-group-item-action">
                        creditos
                    </a>

                @endif
            </div>

        </div>
</div>